/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppReportsRouteImport } from './routes/app/reports'
import { Route as AppQuickbooksContactSyncRouteImport } from './routes/app/quickbooks-contact-sync'
import { Route as AppPayablesRouteImport } from './routes/app/payables'
import { Route as AppCompanyRouteImport } from './routes/app/company'

const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppQuickbooksContactSyncRoute =
  AppQuickbooksContactSyncRouteImport.update({
    id: '/quickbooks-contact-sync',
    path: '/quickbooks-contact-sync',
    getParentRoute: () => AppRoute,
  } as any)
const AppPayablesRoute = AppPayablesRouteImport.update({
  id: '/payables',
  path: '/payables',
  getParentRoute: () => AppRoute,
} as any)
const AppCompanyRoute = AppCompanyRouteImport.update({
  id: '/company',
  path: '/company',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/company': typeof AppCompanyRoute
  '/app/payables': typeof AppPayablesRoute
  '/app/quickbooks-contact-sync': typeof AppQuickbooksContactSyncRoute
  '/app/reports': typeof AppReportsRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/company': typeof AppCompanyRoute
  '/app/payables': typeof AppPayablesRoute
  '/app/quickbooks-contact-sync': typeof AppQuickbooksContactSyncRoute
  '/app/reports': typeof AppReportsRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/company': typeof AppCompanyRoute
  '/app/payables': typeof AppPayablesRoute
  '/app/quickbooks-contact-sync': typeof AppQuickbooksContactSyncRoute
  '/app/reports': typeof AppReportsRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/company'
    | '/app/payables'
    | '/app/quickbooks-contact-sync'
    | '/app/reports'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/company'
    | '/app/payables'
    | '/app/quickbooks-contact-sync'
    | '/app/reports'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/company'
    | '/app/payables'
    | '/app/quickbooks-contact-sync'
    | '/app/reports'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/quickbooks-contact-sync': {
      id: '/app/quickbooks-contact-sync'
      path: '/quickbooks-contact-sync'
      fullPath: '/app/quickbooks-contact-sync'
      preLoaderRoute: typeof AppQuickbooksContactSyncRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/payables': {
      id: '/app/payables'
      path: '/payables'
      fullPath: '/app/payables'
      preLoaderRoute: typeof AppPayablesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/company': {
      id: '/app/company'
      path: '/company'
      fullPath: '/app/company'
      preLoaderRoute: typeof AppCompanyRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppCompanyRoute: typeof AppCompanyRoute
  AppPayablesRoute: typeof AppPayablesRoute
  AppQuickbooksContactSyncRoute: typeof AppQuickbooksContactSyncRoute
  AppReportsRoute: typeof AppReportsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCompanyRoute: AppCompanyRoute,
  AppPayablesRoute: AppPayablesRoute,
  AppQuickbooksContactSyncRoute: AppQuickbooksContactSyncRoute,
  AppReportsRoute: AppReportsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
